[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
PYTHONUNBUFFERED = "1"
TF_CPP_MIN_LOG_LEVEL = "2"
