[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
PYTHONUNBUFFERED = "1"
TF_CPP_MIN_LOG_LEVEL = "2"
TF_FORCE_GPU_ALLOW_GROWTH = "true"
OMP_NUM_THREADS = "1"
TF_NUM_INTEROP_THREADS = "1"
TF_NUM_INTRAOP_THREADS = "1"
